platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

target 'AliyunFaceAuthDemo' do
  pod 'SnapKit', '~> 5.6'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
